#!/usr/bin/env bats

@test "/etc/yum.conf is created by Chef" {
  cat /etc/yum.conf | grep 'Generated by Chef'
}

@test "elrepo is created" {
  [ -f /etc/yum.repos.d/elrepo.repo ]
}

@test "epel is created" {
  [ -f /etc/yum.repos.d/epel.repo ]
}

@test "ius is created" {
  [ -f /etc/yum.repos.d/ius.repo ]
}

@test "remi is created" {
  [ -f /etc/yum.repos.d/remi.repo ]
}

@test "rpmforge is created" {
  [ -f /etc/yum.repos.d/rpmforge.repo ]
}

# Cook 2121
@test "zenoss-add.repo file is not updated" {
  [ ! -s /etc/yum.repos.d/zenoss-add.repo ]
}

@test "zenoss-create file is updated" {
  cat /etc/yum.repos.d/zenoss-create.repo | grep baseurl=http://dev.zenoss.com/yum/stable/
}

